#remote_theme: pages-themes/architect@v0.2.0
#plugins:
#- jekyll-remote-theme # add this line to the plugins list if you already have one
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Cognition in AI - Links and resources to Neuro-symbolic computing 
description: Your hub for neuro-symbolic AI- Explore links, papers, and articles with a focus on AI cognition. Contribute and stay updated.
math_engine: mathjax
